universe = docker
docker_image = pytorch/pytorch:2.3.1-cuda12.1-cudnn8-devel
executable = /bin/bash
arguments = /home/atml_team044/tml26_task2/condor/run_master_score.sh
output = /home/atml_team044/tml26_task2/runlogs/master_score.$(ClusterId).out
error = /home/atml_team044/tml26_task2/runlogs/master_score.$(ClusterId).err
log = /home/atml_team044/tml26_task2/runlogs/master_score.log
should_transfer_files = YES
request_CPUs = 2
request_memory = 16G
requirements = UidDomain == "cs.uni-saarland.de"
+WantGPUHomeMounted = true
+WantScratchMounted = true
queue 1
