universe = docker
docker_image = pytorch/pytorch:2.3.1-cuda12.1-cudnn8-devel
executable = /bin/bash
arguments = /home/atml_team044/tml26_task2/condor/setup_python_env.sh
output = /home/atml_team044/tml26_task2/runlogs/setup_python_env.$(ClusterId).out
error = /home/atml_team044/tml26_task2/runlogs/setup_python_env.$(ClusterId).err
log = /home/atml_team044/tml26_task2/runlogs/setup_python_env.log
should_transfer_files = YES
request_CPUs = 2
request_memory = 8G
requirements = UidDomain == "cs.uni-saarland.de"
+WantGPUHomeMounted = true
+WantScratchMounted = true
queue 1
